name: Echo String Workflow

on:
  push:
    branches:
      - BTWCT-22222-change-to-test-the-commit
jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Echo a message
        run: echo "${{ github.event.inputs.message }}"
