name: Auto Sync Feature Branch with Develop

on:
      push:
        branches:
          - BTWCT-45643-new-changes

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Fetch latest changes from develop
        run: git fetch origin develop:develop

      - name: Switch to feature branch
        run: |
          feature_branch="BTWCT-45643-new-changes"
          git checkout "$feature_branch"
          git merge develop --no-edit

      - name: Push changes to feature branch
        run: git push origin "$feature_branch"
