name: On-Demand Workflow

on:
  push:
    branches:
      -  develop
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a custom command
        run: |
          git checkout BTWCT-45643-new-changes
          git merge --no-ff origin/develop
          git push origin BTWCT-45643-new-changes
          echo "feature branch is upto date"
          # Add your custom commands and scripts here
